Add a new 'size' property to change the size of icons on map widgets
chairemobilite/evolution pull request #109
Opened 2023-05-22 16:07 UTC by davidmurray

This adds the necessary functionality to fix issue https://github.com/chairemobilite/od_mtl_2023/issues/401.

Tests currently fail... not quite sure why.

2023-05-23 14:56 UTC, tahini requested changes

2023-05-23 19:02 UTC, davidmurray commented
Thanks for the comments @tahini 
Fixed the problems and rebased. :)

2023-05-29 14:48 UTC, davidmurray commented
@tahini Ready for merge

2023-05-29 14:55 UTC, tahini approved these changes

2023-05-29 14:55 UTC, merged