Map fixes
chairemobilite/evolution pull request #145
Opened 2023-07-07 17:58 UTC by davidmurray

2023-07-11 17:35 UTC, tahini requested changes
I trust you tested it properly. Just please extract numbers to constant, with names that mean something for the reader later.

2023-07-11 17:35 UTC, tahini commented on packages/evolution-frontend/src/components/inputs/maps/google/GoogleGeocoder.tsx
> +        const searchRadius = Math.min(Math.max(viewportRadius, 500), 8000);
There are meters? Could you extract the 500 and 8000 in constants with a meaningful name

2023-07-11 19:52 UTC, davidmurray commented
@tahini Fixed! I think we can merge this :) thanks!

2023-07-12 18:24 UTC, davidmurray commented on packages/evolution-frontend/src/components/inputs/maps/google/GoogleGeocoder.tsx
> +const geocodingSearchRadiusMaximum = 8000;
@tahini 
Non, c'est uniquement une suggestion pour Google.
S'il n'y a pas de résultats dans ce rayon, l'API va quand même retourner des résultats.
Voir https://developers.google.com/maps/documentation/places/web-service/search-text

> `radius`
> Defines the distance (in meters) within which to return place results. You may bias results to a specified circle by passing a location and a radius parameter. Doing so instructs the Places service to _prefer_ showing results within that circle; results outside of the defined area may still be displayed. 

On utilise le rayon de recherche ici pour prioriser les lieux qui sont dans la zone visible actuellement sur la carte. Si on ne fixe pas ce rayon, Google nous propose des cafés à Kirkland quand la carte est zoomée sur Rosemont. Pas super pratique.
Voir video ci-dessous. Si on est loin, on trouve quand même des résultats en dehors du 8 km:
https://github.com/chairemobilite/evolution/assets/545502/7789ada7-5823-490e-8bac-482d4b5a260a

2023-07-17 13:34 UTC, merged