Fix language not saved
chairemobilite/evolution pull request #174
Opened 2023-07-28 13:55 UTC by davidmurray

Based on my small scale testing, this seems to fix the issue. In my database, _language was always null, but now it seems to correctly show "fr" or "en". Fixes https://github.com/chairemobilite/od_mtl_2023/issues/374

@kaligrafy @tahini : any clue why the code was like that in the first place? Since the migration from transition-legacy, I can't git blame properly (or am I unaware of a feature of git?)

2023-07-28 14:14 UTC, kaligrafy commented
No idea. It worked for some interviews though

2023-07-28 14:15 UTC, kaligrafy commented
I thinkg there was a bug with i18n that was not returning the language. Can you confirm it is correctly set by i18n on every launch?

2023-07-28 17:31 UTC, tahini requested changes
I think a change in i18n configuration now allows to better detect the language at startup, which was not the case before. So it should work now.

You'll probably have to mock the i18n package in the failing test though.

2023-08-15 18:42 UTC, kaligrafy commented
@tahini why it does not compile?

2023-08-16 01:42 UTC, tahini commented
> @tahini why it does not compile?

It compiles, but the test fails because the i18n needs to be mocked.

2023-08-18 14:06 UTC, kaligrafy commented
Je te l'assigne @tahini, tu pourra sme montrer comment faire le mock pour la prochaine fois :-)

2023-08-24 21:02 UTC, tahini commented
Replaced with #212 which adds the test fix

2023-08-24 21:02 UTC, closed without merging