redesign login page (simplify)
chairemobilite/evolution pull request #189
Opened 2023-08-09 13:48 UTC by kaligrafy

2023-08-09 15:29 UTC, tahini requested changes
les fichiers .json et `_base.scss` ont été reformatés au complet. Serait-il possible d emettre l'indentation originale pour bien voir les différences

2023-08-09 18:26 UTC, tahini commented
Voici de quoi ça a l'air avec demo_survey: 

![Capture d’écran du 2023-08-09 14-25-02](https://github.com/chairemobilite/evolution/assets/4398897/0e432063-2d95-4104-a733-bb53b04076dc)

1- Veut-on vraiment voir le texte en-dessous? (surtout le lien Utiliser l'authentification avec mot de passe, le reste du texte est pertinent)

2- Il ne devrait pas y avoir qqc à côté du "Attention:"?

2023-08-09 18:53 UTC, tahini requested changes
ça fonctionne bien avec plusieurs variantes de méthodes possibles. Si ni passwordless, ni localLogin ne sont disponibles, il y a une boîte vide qui s'affiche, mais rien de dramatique là-dedans, on peut fixer plus tard.

Par contre, le texte pour switcher de localLogin à passwordless devrait être dans la première boîte, au lieu d'en bas du formulaire je pense.

2023-08-09 18:53 UTC, tahini commented on packages/evolution-frontend/src/components/pages/auth/AuthPageHOC.tsx
> +                        )}
Ces textes (pour passwordless et localLogin) devraient plutôt être dans la boîte des méthodes locales (la première), au lieu d'en bas complètement. D'ailleurs, si on met mettons anonyme comme méthode par défaut, la première boîte est vide.

2023-08-09 19:17 UTC, kaligrafy commented on packages/evolution-frontend/src/components/pages/auth/AuthPageHOC.tsx
> +                        )}
IL faut juste bouger les locales vers evolution/transition j'imagine. J'ai seulement testé avec od_mtl_2023 donc les textes sont là.

2023-08-09 19:18 UTC, kaligrafy commented on packages/evolution-frontend/src/components/pages/auth/AuthPageHOC.tsx
> +                        )}
Le texte dessous est déscativé dans od_mtl_2023

2023-08-09 19:23 UTC, tahini commented
Je parle de la boîte de méthodes d'authentification locales, voir screenshot: déplacer le texte là.

![Capture d’écran du 2023-08-09 14-25-02](https://github.com/chairemobilite/evolution/assets/4398897/a2af8080-97e5-4418-8cb4-91ee7a0ded97)

2023-08-15 18:40 UTC, kaligrafy commented on packages/evolution-frontend/src/components/pages/auth/AuthPageHOC.tsx
> +                        )}
C'est réglé

2023-08-16 01:30 UTC, tahini approved these changes
There's an issue when we use localLogin and change from register to login, but since we don't use both in our current survey, we can fix it later

2023-08-16 01:30 UTC, tahini commented on packages/evolution-frontend/src/components/pages/auth/AuthPageHOC.tsx
> +                            {config.auth.anonymous === true &&
Ce check est redondant avec la ligne plus haut

2023-08-16 01:31 UTC, merged