make sure loading state is 0 before focusing on invalid field, closin…
chairemobilite/evolution pull request #199
Opened 2023-08-15 20:34 UTC by kaligrafy

…g #161

2023-08-21 01:49 UTC, tahini commented
What tests need to be done and what kind of side effects should tests look for?

2023-08-21 12:15 UTC, kaligrafy commented
We just need to make sure it always work when a question is invalid anytime in the workflow

2023-08-25 17:51 UTC, tahini requested changes
It seems to indeed fix issue #161, but could you add to the commit message why it does so? Why does changing a response produce a loadingState > 0, but clicking the submit button brings the loadingState to 0? it's hard to see the link between the issue and the solution right now...

2023-08-27 02:30 UTC, tahini approved these changes

2023-08-27 10:03 UTC, merged