allow the use of enter key or space bar when a button is focused
chairemobilite/evolution pull request #208
Opened 2023-08-22 16:51 UTC by kaligrafy

for better accessibility. Note that the enter key is still disabled if the button is not focused with the tab key

2023-08-22 17:02 UTC, kaligrafy commented
associated with https://github.com/chairemobilite/transition/pull/703

2023-08-24 16:45 UTC, tahini commented on packages/evolution-legacy/src/components/survey/Button.js
> +          onKeyUp = {(e) => { if (e.key === 'enter' || e.key === 'space' || e.which === 13 || e.which === 32) { this.onClickButton(); } else { return; } }}
`yarn format` please

2023-08-24 16:46 UTC, tahini requested changes
Run `yarn format` on the code

2023-08-24 16:48 UTC, kaligrafy commented
formatted

2023-08-25 02:30 UTC, tahini commented on packages/evolution-legacy/src/components/survey/Button.js
> +          onKeyUp = {(e) => { if (e.key === 'enter' || e.key === 'space' || e.which === 13 || e.which === 32) { this.onClickButton(); } else { return; } }}
haha, c'est même pas la ligne que j'attendais qui a été formatée!

2023-08-25 02:30 UTC, tahini approved these changes

2023-08-25 11:08 UTC, merged