Fix 135: add revalidation ("questionable") field.
chairemobilite/evolution pull request #257
Opened 2023-09-18 23:05 UTC by millette

2023-09-20 18:56 UTC, tahini requested changes
Ce serait à confirmer si on veut flagger l'entrevue seulement si elle a été validée ou non, mais je crois qu'on pourrait vouloir tagger aussi une entrevue invalide.

Aussi, il manque les traductions pour ce filtre

![Capture d’écran du 2023-09-20 14-49-57](https://github.com/chairemobilite/evolution/assets/4398897/17448e06-79fd-4a5c-bd94-60f0426aeef8)

cc @harcding Cette PR est pour le flag par entrevue pour un 2e regard. Si possible de spécifier le besoin exact. 

Aussi, enlever de cette branche les changements dans Transition, qui reviennent en arrière, tu peux faire `yarn reset-submodules`

2023-09-20 18:56 UTC, tahini commented on packages/evolution-legacy/src/components/admin/validation/ValidationLinks.js
> +      {interviewIsValid === true && <React.Fragment>{" "}&nbsp;&nbsp;<a href="#" className={`_red${interviewIsQuestionable === false ? ' _active-background' : ''}`} title={t('admin:UnsetQuestionable'
is_questionable ne devrait pas dépendre de is_valid puisqu'on va vouloir tagger l'entrevue sans nécessairement devoir statuer sur sa validité ou non avant. Aussi, ce ne sera pas juste si l'entrevue est valide, mais aussi si invalide (juste pas null je pense, ce serait à confirmer avec les demandeurs)

2023-09-20 19:37 UTC, harcding commented
Je tente de répondre clairement, mais m'appeler si ça ne l'est pas. 
Pour historique, on avait demandé la création d'un bouton pour marquer qu'une entrevue doit être revalidée quand on a remarqué que plein d'enquêtes 'simplifiées' de 2022 avaient des loop infini dedans et qu'on attendait une solution pour pouvoir les traiter. C'est encore un cas possible d'utilisation d'un tel bouton (marquer qu'il y a un glitch dans l'enquête et qu'on doit y revenir quand une solution côté Chaire est apportée), mais hors contexte de glitch, ça sera aussi très utile en validation pour indiquer à un super-validateur ou admin que le valideur qui l'a regardé a une question ou ne sait pas quoi faire avec XYZ partie de l'enquête. Ça serait comme un mécanisme "d'escalation", où un/une validateur/trice regarde une enquête, apporte des mods, mais au lieu de m'envoyer un courriel ou un message Teams pour me demander de regarder de quoi, tag l'enquête comme nécessitant une intervention de plus haut niveau. Quand j'ai le temps, je peux aller regarder que ces enquêtes et régler ces problèmes plus complexes.

2023-09-20 20:38 UTC, millette commented
@harcding pour l'interface j'ai mis dans la liste d'entrevues:

![interface liste d'entrevues](https://user-images.githubusercontent.com/4398897/269388943-17448e06-79fd-4a5c-bd94-60f0426aeef8.png)

As-tu un texte que tu préfèrerais pour les labels? En fait, c'est à 2 endrois, soit dans la sélection (liste d'entrevues) et sur chaque entrevue on a un bouton pour flagger/unflagger.

@tahini Je peux ouvrir un 2e issue pour ceci, mais je trouvais ça étrange d'avoir 2 boutons pour les actions dans chaque entrevue (valider et invalider, compléter et non-compléter et maintenant questionable et non-questionable) avec des fonds rouges/verts selon l'état. Est-ce qu'on ne pourrait pas réduire ça à un seul toggle par action?

2023-09-20 20:52 UTC, harcding commented
Pas certain de suivre @millette , désolé... Mais si j'ai compris, d'accord avec toi que ça soit un toggle (on/off) pour "questionable"/ requires additional review. 
Icone de ce style?
![image](https://github.com/chairemobilite/evolution/assets/18583806/b8fff986-abe0-4be7-ae00-f10a128e165e)

En lien: le bouton 'close' est inutile et pourrait être enlevé. À ma compréhension les changements sont effectués en temps réel, donc je ne vois pas ce que fait 'Close' que ne rien faire ne ferait pas. 
![image](https://github.com/chairemobilite/evolution/assets/18583806/168f2275-9acb-403a-adee-32fc4ccb655c)

2023-09-20 20:55 UTC, harcding commented
Et quand c'est cliqué/toggled, il serait alors possible de filtrer par "re-review required" toggled on. 
Pour les traductions ou le texte en général, on n'y porte pas grand attention, mais "re-review reqd"/"val add requis" serait une proposition. Questionable/douteux est ok aussi si préféré.

2023-09-20 21:04 UTC, millette commented
![2023-09-20-165728_956x933_scrot-crop](https://github.com/chairemobilite/evolution/assets/50741/b633bbf1-0f3f-456b-9e11-3f6a6028a2c5)

Pour le moment j'avais pris les ? dans un cercle, les icons sont tous tirés de <https://fontawesome.com/v5/search?q=question&o=r&m=free>. On peut utiliser 2 icones alors je combinerais avec <https://fontawesome.com/v5/icons/hand-paper?f=classic&s=regular>.

2023-09-22 11:51 UTC, tahini commented
@millette Je n'ai pas trop d'opinion côté texte, entre re-review required ou questionable/douteux.

Pour le toggle, dans le cas de questionable, ou c'est réellemen un booléen, un seul bouton on/off. Par contre, les autre (validé/pas validé, confirmé/pas confirmé), ce sont des 3 états, null, false, true. À voir si possible de rendre ça plus clair, mais c'est pas prioritaire imho.

Pour le bouton close, on le garde, il permet de faire disparaître le sommaire des entrevues et ne voir que la liste.

2023-09-25 12:04 UTC, tahini requested changes
Ce serait bien si cette PR pouvait entrer, même imparfaite, avant les mises en ligne de cette semaine (donc aujourd'hui idéalement). Ce qu'il faut minimalement:

* Rebaser sur main et ne pas committer le retour en arrière de transition (faire un `yarn reset-submodules` après le rebase)
* S'assurer que les tests et le lint passent
* Enlever qq console.log dans survey.js

Le reste peut se faire dans un PR séparé

2023-09-25 21:13 UTC, millette commented
@tahini rebase ça reste un mystère pour moi. Je comprends en principe les branches et l'historique mais sur le terrain, rebase me cause plus de conflits qu'il n'en règle. Je m'ennuie de darcs et comment j'aimerais utilise pijul. **Sigh** Faut faire avec git (que, malgré tout, j'utilise depuis plus de 15 ans mais dont j'évite les méandres).

Tout ça pour dire, j'ai pushé sur une autre branche parce que j'étais *tout pogné* :-(

Les fixes demandés sont ici: https://github.com/millette/evolution/tree/fix-135-linter

Tellement d'endroits où il fallait ajouter ```is_questionable```/```isQuestionable```, j'aurais préféré refactoriser mais vu que le code marche et qu'il y a autant de petits détails, je ne me suis pas lancé là dessus.

Je suis en train d'écrire un romain, pardonnez moi.

2023-09-25 23:12 UTC, millette commented on packages/evolution-legacy/src/actions/survey/survey.js
> +  console.log("sectionShortname", sectionShortname)
Done, voir <https://github.com/chairemobilite/evolution/pull/270>

2023-09-26 22:09 UTC, millette commented
On peut fermer ici et #270, j'ai *encore* pousser sur une autre branche #272 mais à l'avenir ça ira mieux!

2023-09-27 11:55 UTC, closed without merging