Interview list filter by date
chairemobilite/evolution pull request #290
Opened 2023-10-04 19:23 UTC by davidmurray

2023-10-04 19:38 UTC, davidmurray commented
Improved UI (commit [abe7cb6](https://github.com/chairemobilite/evolution/pull/290/commits/abe7cb69a6862101c7fcc030a5768424115e1546))
<img width="532" alt="image" src="https://github.com/chairemobilite/evolution/assets/545502/2e37b7b2-8966-488d-aa42-d5f20d2cecac">

2023-10-04 19:48 UTC, davidmurray commented
weird error in lint process:
"   8:20  error    "moment" is extraneous                     node/no-extraneous-import"

... but it is being used... Hm

2023-10-05 12:16 UTC, tahini commented
Le pakcage 'moment' n'est probablement pas dans le package.json de evolution-frontend. Il faut le rajouter. Attention de bien mettre la même version qu'ailleurs!

2023-10-05 12:53 UTC, tahini commented
le `extract epoch` retourne le timestamp a`la seconde (ou ms) près et n'est pas fait pour comparer avec du = à moins d,être extrêmement chanceux, mais si on compare avec des < ou >, alors ça devrait marcher. D'ailleurs un date range est probablement plus approprié ici. Le changement à la requête a peut-être aussi un impact sur d'autres calls à cette fonction qui utilisaient le timestamp?

2023-10-05 12:55 UTC, tahini commented on packages/evolution-frontend/src/components/pageParts/validations/InterviewByDateFilter.tsx
> +            <DatePicker
See the RefreshInterviewerCache for a datePicker for a range

2023-10-05 16:08 UTC, davidmurray commented
@tahini  fixed :) ready for review.
Now it accepts a date range

2023-10-05 20:10 UTC, tahini requested changes
Sequential tests now fail since the query has changed its format. Also, a db test should be added to cover this case too.

To run sequential tests, you need to run `yarn setup-test && yarn migrate-test && yarn test:sequential`

2023-10-05 20:21 UTC, tahini commented
Also, if you change the format of the created_at date, you could also change the format of the updated_at, which is similar.

2023-10-05 20:36 UTC, davidmurray commented on packages/evolution-frontend/package.json
> +    "react-datepicker": "^4.18.0",
yes. Old version had a bug where the input field would only show the start date of the interval, whereas this version correctly shows the start and end dates

2023-10-06 14:45 UTC, davidmurray commented
@tahini I re-worked the code to use unix timestamps now instead of just a date. This allows more specific filtering (unused now, but could be in the future).
This fixes the tests. I also added a new test to check if we can filter for a range of dates.

2023-10-06 15:14 UTC, davidmurray commented
@tahini rebased to remove upgrade of react-datepicker :)

2023-10-06 17:27 UTC, tahini approved these changes
Thanks!

2023-10-06 17:27 UTC, merged