Generic widgets
chairemobilite/evolution pull request #330
Opened 2023-10-20 15:34 UTC by davidmurray

2023-10-20 16:08 UTC, kaligrafy approved these changes

2023-11-10 16:31 UTC, tahini requested changes
Small details to fix, otherwise, looks good.

@samuel-duhaime Do you think this approach is compatible with the data-driven surveys you are working on? We could have in evolution generic configurable high-level widgets that can be [metaphorically] dragged-and-dropped in the surveys, to avoid having to define them completely and have "nice defaults" (for labels, formats, types, paths, etc).

2023-11-10 16:31 UTC, tahini commented on packages/evolution-frontend/src/components/genericWidgets/home.tsx
> +export const contactEmailInvalidAddressValidation = function(value: string) {
Maybe don't include "contact" in the name here, as it could be used for other email widgets. `isEmailValidValidation` maybe?

2023-11-10 16:31 UTC, tahini commented on packages/evolution-frontend/src/components/genericWidgets/home.tsx
> +    datatype: 'string',
You can use your new `keyboardInputMode` here too

2023-11-10 16:42 UTC, samuel-duhaime commented
> Small details to fix, otherwise, looks good.
> 
> @samuel-duhaime Do you think this approach is compatible with the data-driven surveys you are working on? We could have in evolution generic configurable high-level widgets that can be [metaphorically] dragged-and-dropped in the surveys, to avoid having to define them completely and have "nice defaults" (for labels, formats, types, paths, etc).

Yes @tahini @davidmurray , it's very easy to implement that. In the Excel widgets tab, we just need to have an InputType "Generic", and we are good to go. :)

2024-12-16 21:44 UTC, greenscientist commented
@tahini , @samuel-duhaime what is the status here?

2024-12-17 15:51 UTC, tahini commented
Anyway, with the widgets moving to evolution, this will change

2025-04-09 17:33 UTC, tahini commented
Closing, as current work makes this deprecated and it would just be harder to rebase anyway

2025-04-09 17:33 UTC, closed without merging