Add template to Generator
chairemobilite/evolution pull request #421
Opened 2024-04-04 20:44 UTC by samuel-duhaime

# Pull request
fix: #414 

## Description
Add template type
Add template to sectionConfigs.ts

2024-04-04 23:12 UTC, tahini requested changes
Could you explain in the commit message or in the README how to add a template? iiuc, we need to put the `template.tsx` file in the survey's corresponding section? And the template should be a React component?

2024-04-05 14:52 UTC, samuel-duhaime commented
> Could you explain in the commit message or in the README how to add a template? iiuc, we need to put the `template.tsx` file in the survey's corresponding section? And the template should be a React component?

Yes, with the commit, I did explain it on 'Project Structure' of the README of Generator.

2024-04-05 16:55 UTC, tahini approved these changes

2024-04-05 17:45 UTC, samuel-duhaime commented on packages/evolution-generator/src/types/sectionsTypes.ts
> +    template?: any;
Non, c'est quelque chose de beaucoup plus compliqué. C'est pour cela que j'ai mis any pour l'instant...

![image](https://github.com/chairemobilite/evolution/assets/78976679/415813c6-6619-4aee-8708-9f1819e009b2)

2024-04-05 17:53 UTC, samuel-duhaime commented on packages/evolution-generator/src/types/sectionsTypes.ts
> +    template?: any;
Je viens d'ouvrir un issue pour cela #424 .

2024-04-05 18:47 UTC, merged