playwright: Add visibility test and fix range test
chairemobilite/evolution pull request #494
Opened 2024-05-15 16:00 UTC by tahini

2024-05-15 19:16 UTC, samuel-duhaime requested changes

2024-05-15 19:16 UTC, samuel-duhaime commented on packages/evolution-frontend/tests/ui-testing/testHelpers.ts
> +export const inputRangeTest: InputRangeTest = ({ path, value, trackClassName = 'input-slider-blue' }) => {
On ne peut pas faire un Regex? Au lieu de devoir écrire input-slider-blue et toutes les autres variations?
Quelque chose comme input-slider-* ?

2024-05-15 19:16 UTC, samuel-duhaime commented on packages/evolution-frontend/tests/ui-testing/testHelpers.ts
> +export const inputVisibleTest = ({ path, isVisible = true }: { path: Path, isVisible?: boolean }) => {
Ah oui, c'est bien ce test!

2024-05-15 19:22 UTC, tahini commented on packages/evolution-frontend/tests/ui-testing/testHelpers.ts
> +export const inputRangeTest: InputRangeTest = ({ path, value, trackClassName = 'input-slider-blue' }) => {
Je ne sais pas, le trackClassName est utilisé dans un locator par css. On pourrait mettre juste le 'blue' ou 'green-yellow-red', mais ça permet en même temps de tester que le style est celui attendu.

2024-05-15 19:25 UTC, samuel-duhaime commented on packages/evolution-frontend/tests/ui-testing/testHelpers.ts
> +export const inputRangeTest: InputRangeTest = ({ path, value, trackClassName = 'input-slider-blue' }) => {
Oui, allons-y pour 'blue' ou 'green-yellow-red', au lieu d'écrire 'input-slider-blue'. Ça va être plus convivial à écrire quand on va devoir réécrire les 200 tests UI.

2024-05-16 14:39 UTC, samuel-duhaime approved these changes

2024-05-16 14:41 UTC, merged