inputRange: add a `includeNonApplicable` property
chairemobilite/evolution pull request #552
Opened 2024-06-18 01:44 UTC by tahini

fixes #539

To avoid the participant having to select a position for a question that does not apply to him, there should be a "Non applicable" option that the user can select that will disable the input range. The answer in this case, instead of a `number` will be a `string` with value `na`.

2024-06-18 01:48 UTC, tahini commented
See the screenshot in the issue for what it looks like. 

Do you think the text of the "Non applicable" is ok? should be overridable by the individual surveys? And if so, should each question be able to update it?

Is `includeNonApplicable` a good name for the property?

There may also be some aria to add somewhere to make sure the "Non applicable" is linked to the text of the question somehow.

2024-06-18 12:24 UTC, kaligrafy commented
The text should be overridable in the survey config

2024-06-18 19:41 UTC, samuel-duhaime requested changes
Peux-tu rajouter dans le Generator, rajouter un row includeNotApplicable?

2024-06-18 19:41 UTC, samuel-duhaime commented on example/demo_survey/src/survey/widgets/end.tsx
>      datatype: "number",
Mettre en anglais. includeNotApplicable 

Comme dit par @kaligrafy, peux-tu ajouter un notApplicableLabel?

2024-06-18 19:41 UTC, samuel-duhaime commented on packages/evolution-common/src/services/widgets/WidgetConfig.ts
> +    includeNonApplicable?: boolean;
Mettre en anglais, includeNotApplicable.

2024-06-18 19:41 UTC, samuel-duhaime commented on packages/evolution-frontend/src/components/inputs/InputCheckbox.tsx
> +    value: string[];
C'était une erreur d'un autre commit?

2024-06-18 19:41 UTC, samuel-duhaime commented on packages/evolution-frontend/src/components/inputs/InputRange.tsx
> +    const [value, setValue] = React.useState<number | Range | undefined | string>(props.value);
On veut un string ou mettre 'na' ?

2024-06-18 19:41 UTC, samuel-duhaime commented on packages/evolution-frontend/src/components/inputs/InputRange.tsx
> +    value?: number | string;
On veut un string ou mettre 'na' ?

2024-06-18 19:41 UTC, samuel-duhaime commented on packages/evolution-frontend/src/components/inputs/__tests__/InputRange.test.tsx
> +describe('Should correctly render InputRange with non applicable', () => {
Mettre en anglais 'not applicable'

2024-06-19 13:10 UTC, tahini commented on packages/evolution-frontend/src/components/inputs/InputRange.tsx
> +    value?: number | string;
Bon point, je vais mettre 'na' seulement

2024-06-19 13:36 UTC, tahini commented
> Peux-tu rajouter dans le Generator, rajouter un row includeNotApplicable?

C'est fait

2024-06-19 13:37 UTC, tahini commented on packages/evolution-frontend/src/components/inputs/InputCheckbox.tsx
> +    value: string[];
C'est un autre commit entier dans cette PR qui corrige une erreur sur ce type qui existe depuis longtemps...

2024-06-19 16:05 UTC, merged