Make the segment section configurable
chairemobilite/evolution pull request #596
Opened 2024-07-12 17:39 UTC by tahini

Details to come...

2024-10-22 19:16 UTC, samuel-duhaime submitted a review, later dismissed

2024-10-22 19:16 UTC, samuel-duhaime commented on packages/evolution-common/src/services/odSurvey/types.ts
I think we should put more information about what this file does. 

odSurvey types are pretty abstract. Types of what exactly ?

2024-10-22 19:16 UTC, samuel-duhaime commented on packages/evolution-frontend/src/assets/images/modes_icons/mobilityScooter.png
Oh, c'est cute.

2024-10-22 19:18 UTC, samuel-duhaime commented
Sorry, I didn't want to accept the review now, because it's still on draft.

2024-10-22 19:19 UTC, samuel-duhaime reviewed
Sorry, I didn't want to accept the review now, because it's still on draft.

2024-10-29 15:55 UTC, tahini commented
@kaligrafy @samuel-duhaime  c'est officiellement prêt pour review

2024-10-29 17:07 UTC, kaligrafy requested changes

2024-10-29 17:07 UTC, kaligrafy commented on locales/en/segments.yml
> +    Taxi: <strong>Taxi</strong> or equivalent (eg. Uber)
include Lyft?

2024-10-29 17:07 UTC, kaligrafy commented on locales/en/segments.yml
> +    DontKnow: <strong>I don't know</strong> / Prefer not to answer
separate: not the same

2024-10-29 17:07 UTC, kaligrafy commented on locales/en/segments.yml
> +        dontKnow: Don't know
add prefer not to answer

2024-10-29 17:07 UTC, kaligrafy commented on locales/en/segments.yml
> +ModeFirst: Which mode of transportation was used first?
use the term "mode of transport" everywhere instead of mode of transportaiton or transportation mean/mean of transport/transportation

2024-10-29 17:07 UTC, kaligrafy commented on locales/fr/segments.yml
> +    CarDriver: <strong>Conducteur</strong> (voiture/moto/scooter)
ajouter camion partout où on a voiture/moto/scooter

2024-10-29 17:07 UTC, kaligrafy commented on locales/fr/segments.yml
> +    Bicycle: <strong>Vélo</strong> ou <strong> Vélo électrique</strong>
retirer l'espace de trop et mettre vélo électirque en minuscule

2024-10-29 17:07 UTC, kaligrafy commented on locales/fr/segments.yml
> +    Taxi: <strong>Taxi</strong> ou équivalent (ex. Uber)
ajouter Lyft?

2024-10-29 17:07 UTC, kaligrafy commented on locales/fr/segments.yml
> +    DontKnow: <strong>Je ne sais pas</strong> / Préfère ne pas répondre
séparer

2024-10-29 17:07 UTC, kaligrafy commented on locales/fr/segments.yml
> +    DontKnow: <strong>Je ne sais pas</strong> / Préfère ne pas répondre
ajouter préfère ne pas répondre

2024-10-29 17:07 UTC, kaligrafy commented on packages/evolution-common/src/services/odSurvey/types.ts
> +    transitGondola: ['transit'],
add "other"

2024-10-29 17:07 UTC, kaligrafy commented on packages/evolution-common/src/services/odSurvey/types.ts
> +    wheelchair: ['walk'],
add "other"

2024-10-29 17:07 UTC, kaligrafy commented on packages/evolution-common/src/services/sections/segments/widgetSegmentModePre.ts
> +            const drivingLicenseOwner =
change the variable name to match value (ownerSHIP)

2024-10-29 17:44 UTC, tahini commented on locales/en/segments.yml
> +    CarDriverPersonal: <strong>Driver</strong> with personal vehicle (car/moto/scooter)
Added, for passenger too I suppose

2024-10-29 17:46 UTC, tahini commented on locales/en/segments.yml
> +    SchoolBus: <strong>School bus</strong> (yellow)
I'll remove, people can override in the customSurvey.yml files for their own surveys

2024-10-29 18:50 UTC, kaligrafy approved these changes

2024-10-29 19:43 UTC, merged