change query for interviewSummary
chairemobilite/evolution pull request #631
Opened 2024-08-07 15:59 UTC by kaligrafy

use getInterviewByUuid instead of getAllMAtching

this makes the query way faster

2024-08-07 15:59 UTC, kaligrafy commented
Please cherry-pick in od_mtl_2023

2024-08-07 17:32 UTC, tahini reviewed
As-tu testé sur demo_survey? ou as-tu testé cette PR sur od_mtl? Car les 2 fonctions ne retournent pas exactement la même chose, getAllMatching avait en plus les infos de google, facebook, ainsi que le user.

2024-08-07 19:02 UTC, tahini requested changes
We need to determine the impacts of changing this. The `getAllMatching` function fetched the audits from the DB, while the `getInterviewByUuid` doesn't. The call of `/validateInterview` uses the `getInterviewByUuid` but triggers the `runAndSaveAudits` function.

Simply changing the call here may have more unforeseen impacts.

2024-08-07 19:40 UTC, tahini commented
ĉa reste à confirmer, mais ftr, quand on appelle `interviewSummary` sur el serveur, la requête suivante est `validateInterview`, donc les audits sont re-roulés. Est-ce que c'est juste sur od_mtl ou c'est codé comme ça dans evolution reste à confirmer avant d'accepter cette PR.

2024-10-04 01:11 UTC, tahini commented
`interviewSummary` is now gone, we don't need this anymore

2024-10-04 01:11 UTC, closed without merging

2024-10-04 01:17 UTC, tahini commented
By "magic", yes, but I didn't try it with a survey with a lot of audition to do, but at least you won't wait too long on the SQL query.