mapFindPlace: Allow multiple geocoding query string and zooms
chairemobilite/evolution pull request #672
Opened 2024-09-09 19:21 UTC by tahini

fixes #665

The `geocodingQueryString` function now returns either a string or an array of objects containing a `queryString` and a `zoom`. The first object is geocoded and if results are returned, they are used and the map zooms at the specified level. If no results are returned, the next query string object is geolocated, etc.

2024-09-09 19:35 UTC, samuel-duhaime requested changes

2024-09-09 19:35 UTC, samuel-duhaime commented on packages/evolution-frontend/src/components/inputs/InputMapFindPlace.tsx
> +                const getFirstGeocodingResult = async () => {
Peux-tu mettre un commentaire. Ce n'est pas clair pour moi, ce que ça fait. 

On veut le premier geocoding result de quoi? Comment on fait pour avoir plusieurs geocoding result ?

2024-09-09 19:42 UTC, tahini commented on packages/evolution-frontend/src/components/inputs/InputMapFindPlace.tsx
> +                const getFirstGeocodingResult = async () => {
En effet, c'est pas clair, on retourne tous les résultats de la première requête qui retourne des résultats.

2024-09-10 13:22 UTC, tahini commented on packages/evolution-frontend/src/components/inputs/InputMapFindPlace.tsx
> +                const getFirstGeocodingResult = async () => {
Ajouté un commentaire et modifié le nom, est-ce plus clair?

2024-09-10 13:34 UTC, kaligrafy commented
Est-ce que c'est backward compatible avc nos enquêtes courantes?

2024-09-10 13:35 UTC, samuel-duhaime approved these changes

2024-09-10 13:50 UTC, tahini commented
> Est-ce que c'est backward compatible avc nos enquêtes courantes?

Bien sûr voyons!

2024-09-10 13:51 UTC, tahini commented on packages/evolution-frontend/src/components/inputs/maps/google/InputMapGoogle.tsx
> +        console.log('using effetc for fit bounds');
`a enlever...

2024-09-10 13:52 UTC, kaligrafy approved these changes

2024-09-10 14:22 UTC, merged