Generator: Format files, remove error when no inputType  and add better error message
chairemobilite/evolution pull request #702
Opened 2024-09-26 20:16 UTC by samuel-duhaime

# Pull request

## Description
Format files, remove error when no inputType  and add better error message.

## Justification
It was hard to debug the Generator when the Excel file was modified with much error.

2024-09-26 23:17 UTC, tahini reviewed
C'est quoi le formatage des fichiers utilisé ici? Est-ce ton éditeur qui le fait automatiquement ? Ce qui veut dire que qqn d'autre pourrait avoir un formatage différent. Ou alors il y a une commande comme `yarn format` pour le faire automatiquement de la même manière pour tous?

2024-09-27 18:33 UTC, samuel-duhaime commented
> C'est quoi le formatage des fichiers utilisé ici? Est-ce ton éditeur qui le fait automatiquement ? Ce qui veut dire que qqn d'autre pourrait avoir un formatage différent. Ou alors il y a une commande comme `yarn format` pour le faire automatiquement de la même manière pour tous?

@tahini 
Non, en effet, il n'y a pas de formatage automatique avec Python. 

Je crois qu'on peut ajouter cette commande au prettier pour y parvenir, mais je n'ai pas testé.

```
"[python]": {
    "editor.defaultFormatter": "ms-python.python"
  }
```

2024-09-27 18:47 UTC, samuel-duhaime commented
@tahini 

Okay, apparament ce code était pour le formatter de utopep8.
Il y a aussi black qui est populaire. Je peux essayer d'installer cela rapidement.

2024-09-27 19:04 UTC, samuel-duhaime commented
@tahini J'ai installé une configuration prettier avec Black qui marche plutôt bien. Pas besoin d'avoir une configuration pour le configurer.

2024-09-27 19:18 UTC, tahini commented
@samuel-duhaime l'idée c'est de ne pas changer le formatage au gré des gens/éditeurs et qu'on ait tous le même format. C'est la beauté de la commande `yarn format`. On oublie de la rouler 80% du temps, ce qui donne des commits intitulés "Run `yarn format` on the code", mais être plus disciplinés, on le saurait et on aurait tous la même chose!

2024-09-27 19:31 UTC, tahini requested changes
Juste un commentaire pour avoir à la fois le formatage typescript et python dans le evolution-generator

2024-09-27 19:31 UTC, tahini commented on packages/evolution-generator/package.json
> -    "format": "prettier-eslint ./src/**/*.{ts,tsx} --write",
Il n'y a pas aussi des fichiers .ts dans evolution-generator qu'il faudrait formater du même coup? Donc garder la commande format et ajouter `format:python`

2024-09-27 19:31 UTC, tahini commented on packages/evolution-generator/src/scripts/generate_section_configs.py
> +                "parent_section",
le formateur _ajoute_ des virgules à la fin des arrays??? J'avoue que c'est surprenant

2024-09-27 19:31 UTC, tahini commented on packages/evolution-generator/src/scripts/generate_widgets.py
> +                has_custom_conditionals_import,
Il ajoute aussi des virgules après le dernier paramètre?

2024-09-27 19:39 UTC, samuel-duhaime commented on packages/evolution-generator/src/scripts/generate_section_configs.py
> +                "parent_section",
@tahini  Oui, Black est un formatteur auquel tous les contributeurs se sont entendus ensemble pour mettre en place le même systême de formattage pour tout le monde. 

Donc, j'imagine que c'est une règle qui a déjà été discutté entre eux et que la conclusion était d'avoir des virgules à la fin.

> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

2024-09-27 19:43 UTC, samuel-duhaime commented on packages/evolution-generator/package.json
> -    "format": "prettier-eslint ./src/**/*.{ts,tsx} --write",
Oui, en effet. C'est fait.

2024-09-27 20:13 UTC, tahini approved these changes

2024-09-27 20:13 UTC, merged