move loading state reducer to evolution-frontend
chairemobilite/evolution pull request #735
Opened 2024-10-16 17:47 UTC by kaligrafy

2024-10-16 18:10 UTC, kaligrafy commented
See https://github.com/chairemobilite/evolution/issues/736

2024-10-16 18:24 UTC, tahini requested changes

2024-10-16 18:24 UTC, tahini commented on packages/evolution-frontend/src/store/loadingState/reducer.ts
> +            loadingState: action.loadingState + 1
La valeur actuelle devrait être dans `state` et non dans `action`

2024-10-16 18:24 UTC, tahini commented on packages/evolution-frontend/src/store/loadingState/reducer.ts
> +            loadingState: action.loadingState - 1
Techniquement, est-ce qu'il faudrait s'assurer que le loadingState ne vient jamais sous zéro?

2024-10-16 18:24 UTC, tahini commented on packages/evolution-frontend/src/store/loadingState/__tests__/reducer.test.ts
> +    expect(loadingStateReducer({ }, action)).toEqual(result);
Le state (1er paramètre) devrait inclure une valeur pour le loadingState

2024-10-16 19:38 UTC, kaligrafy commented on packages/evolution-frontend/src/store/loadingState/reducer.ts
> +            loadingState: action.loadingState + 1
fixed

2024-10-16 19:38 UTC, kaligrafy commented on packages/evolution-frontend/src/store/loadingState/__tests__/reducer.test.ts
> +    expect(loadingStateReducer({ }, action)).toEqual(result);
fixed

2024-10-16 19:38 UTC, kaligrafy commented on packages/evolution-frontend/src/store/loadingState/reducer.ts
> +            loadingState: action.loadingState - 1
fixed

2024-10-16 20:30 UTC, tahini approved these changes

2024-10-16 20:30 UTC, tahini commented on packages/evolution-frontend/src/store/loadingState/__tests__/reducer.test.ts
> +test('Test decrement loading state', () => {
Ce serait bien d'avoir un test pour les valeurs négatives aussi

2024-10-17 16:40 UTC, kaligrafy commented on packages/evolution-frontend/src/store/loadingState/__tests__/reducer.test.ts
> +test('Test decrement loading state', () => {
ajouté

2024-10-17 17:22 UTC, merged