Move admin components from legacy
chairemobilite/evolution pull request #764
Opened 2024-10-31 14:34 UTC by kaligrafy

2024-10-31 14:34 UTC, kaligrafy commented
Do not review yet, needs moving of files that are temporary disabled

2024-10-31 15:45 UTC, tahini requested changes

2024-10-31 15:45 UTC, tahini commented on packages/evolution-frontend/src/components/admin/monitoring/StartedAndCompletedInterviewByDay.tsx
> +                this.state.data.completedCount !== undefined &&
J'ai l'impression que `yarn format` a changé qqc ici

2024-10-31 15:45 UTC, tahini commented on packages/evolution-frontend/src/components/admin/export/AdminExportPage.tsx
> +    onUpdate() {
Est-ce que cette fonction est utilisée? Ce composant peut probablement être un function component au lieu d'une classe

2024-10-31 15:45 UTC, tahini commented on packages/evolution-frontend/src/components/admin/monitoring/AdminMonitoringPage.tsx
> +            <React.Fragment>
Un fragment dans qqc qui s'appelle "Page", c'est peut-être mal nommé?

2024-10-31 15:45 UTC, tahini commented on packages/evolution-frontend/src/components/admin/monitoring/AdminMonitoringPageContainer.tsx
> +    user: CliUser;
C'est plus celui-ci qui devrait s'appeler `Page` et l'autre `Container`

2024-10-31 15:45 UTC, tahini commented on packages/evolution-frontend/src/components/admin/monitoring/widgets/StartedAndCompletedInterviewByDay.tsx
> +            this.state.data.completedCount !== undefined &&
Ceci allait probablement dasn le commit d'avant... avec le formatage réglé

2024-10-31 15:45 UTC, tahini commented on packages/evolution-legacy/src/components/admin/Validation.js
> +    return <p>Validation.js legacy (to be replaced)</p>;
Pourquoi commenter l'output initial? ça ne fonctionne pas?

2024-10-31 15:45 UTC, tahini commented on packages/evolution-legacy/src/apps/admin/client/SurveyRouter.js
> +    <PrivateRoute  path="/admin/survey/:sectionShortname" permissions={{ 'Interviews': ['review'] }} component={AdminValidateSurveyPage} exact={true} />
Ce serait pas 'correct' ici aussi?

2024-10-31 15:45 UTC, tahini commented on packages/evolution-backend/src/services/auth/participantAuthorization.ts
> +export type permissionType = 'read' | 'update' | 'review' | 'correct' | 'export' | 'confirm' | 'delete' | 'create';
Ceci est pour un participant, en fait read, create et update devraient être les seules permissions permises pour un participant. D'ailleurs ce type ne semble utilisé nulle part, la fonction interviewParticipantIsAuthorized semble juste valider que l'entrevue demandée est bien celle du participant et dire qu'il y a droit. Peut-être qu'il faudrait ajouter le spermissions en paramètre du `interviewParticipantIsAuthorized` pour s,assurer qu'on ne demande par accident des permissions trop élevées pour un simple participant. En tk, pour une autre fois peut-être, mais tu peux enlever ce type sans problème je crois.

2024-10-31 17:36 UTC, samuel-duhaime commented on packages/evolution-frontend/src/components/admin/monitoring/AdminMonitoringPage.tsx
> +            <React.Fragment>
Un simple div aurait fait l'affaire dans ce cas.

2025-04-09 17:31 UTC, tahini commented
evolution-legacy n'existe plus

2025-04-09 17:31 UTC, closed without merging