Fix demo_survey UI tests, type SectionConfig and remove hiddenInNav
chairemobilite/evolution pull request #789
Opened 2024-11-19 21:54 UTC by tahini

This PR verifies all sections completion and enablement in the `SectionNav`, thus fixing the UI tests failures since it was moved to typescript

It also completes the typing of the SectionConfig, adding the missing fields

The `hiddenInNav` property is removed, in favor of a parentSection's check, such that only sections without parents are in the navigation bar.

2024-11-19 21:56 UTC, tahini commented
@samuel-duhaime  ça affecte le générateur, j'ai testé avec longue distance et ça a l'air beau. Pourrais-tu voir si mettons avec dependance à l'auto si la présence du parentSection et le hiddenInNav vont vraiment de pair (hiddenInNav: true <=> parentSection is defined et hiddenInNav: false <=> parentSection undefined), ou si c'est possible/sensé d'avoir d'autres combinaisons?

2024-11-19 22:19 UTC, samuel-duhaime requested changes
I'm not sure about the change from 'undefined' to 'null,' but you might convince me if you have a good reason.

2024-11-19 22:19 UTC, samuel-duhaime commented on packages/evolution-generator/src/scripts/generate_sections.py
> +        ts_code += f"import {{ SurveySections }} from 'evolution-frontend/lib/services/interviews/interview';\n"
f­­­­"" is less performing, no? 
It's not a big deal. No need to change that.

2024-11-19 22:19 UTC, samuel-duhaime commented on packages/evolution-generator/README.md
Line 308: export const sectionConfig: SectionConfig = {

I believe it’s no longer adequate (the type name has changed). There may be a few other mistakes in the README.

2024-11-19 22:19 UTC, samuel-duhaime commented on packages/evolution-generator/README.md
> -    },
Are you sure about this one ?

Did you change anything with groups?

2024-11-19 22:19 UTC, samuel-duhaime commented on packages/evolution-frontend/src/services/interviews/interview.ts
> +    previousSection: string | null;
Why `previousSection: string | null; `and not `previousSection?: string;` ?

2024-11-19 22:19 UTC, samuel-duhaime commented on packages/evolution-frontend/src/components/survey/sectionTemplates/__tests__/TripsAndSegmentsSection.test.tsx
That's strange no? No previousSection but also no nextSection. There are only 1 section in this test ?

Not sure, I'm a fan of 'previousSection: null,'.
Why generate code like this.

2024-11-19 22:20 UTC, samuel-duhaime commented
> @samuel-duhaime ça affecte le générateur, j'ai testé avec longue distance et ça a l'air beau. Pourrais-tu voir si mettons avec dependance à l'auto si la présence du parentSection et le hiddenInNav vont vraiment de pair (hiddenInNav: true <=> parentSection is defined et hiddenInNav: false <=> parentSection undefined), ou si c'est possible/sensé d'avoir d'autres combinaisons?

@tahini Non, c'est beau avec ta nouvelle méthode. Je n'ai pas encore vu d'enquête qu'on a fait cela, c'est probablement un signe que ce n'est pas nécessaire.

2024-11-19 22:23 UTC, samuel-duhaime commented
@tahini 

Je crois qu'il y a un BREAKING CHANGE. 
Minimalement, les prochaines enquêtes mises à jour vont devoir faire 'yarn generateSurvey' car certaines importations ont changé.

2024-11-20 14:07 UTC, tahini reviewed
So what should we decide:

`previousSection?: string` or `previousSection: string | null`. It has implications. Same for `nextSection`. I don't have absolute preference: `string | null` forces us to think on the value, otherwise we could have just forgotten.

2024-11-20 14:07 UTC, tahini commented on packages/evolution-generator/README.md
> Line 308: export const sectionConfig: SectionConfig = {
> 
> I believe it’s no longer adequate (the type name has changed). There may be a few other mistakes in the README.

The SectionConfig has not changed its named, it's just from a different import, but the SectionName does not exist anymore. I'll update the doc.

2024-11-20 16:06 UTC, samuel-duhaime approved these changes
Ça me semble bien.

2024-11-20 16:11 UTC, merged