sections: Type the `template` to a string that maps to component
chairemobilite/evolution pull request #808
Opened 2024-11-27 21:24 UTC by tahini

Now that the `SectionConfig` type is in the evolution-common package, it cannot have a React component as field. Instead, we use a name for the template and map it to the component in the config.

Add the `templateMapping` application configuration in the frontend that maps the template names to a template component.

This incidentally allows to provide different section templates for the admin and participant apps.

The `TripsAndSegmentsSection` template is named
`tripsAndSegmentsWithMap` and the application configures it when it bootstraps.

** Breaking change **

Surveys that use section templates need to update their configuration

In the section configuration, replace the `template` field to be a string instead. For example ` template: SegmentSection` becomes ` template: 'tripsAndSegmentsSection'`.

If the survey provides additional templates, the frontend application's entry file need to configure the mapping.

For example, in `demo_survey`, the `app-survey.tsx` and the `app-admin.tsx`  files now contain this code:

```
import appConfig, { EvolutionApplicationConfiguration } from 'evolution-frontend/lib/config/application.config';
import { setApplicationConfiguration } from 'chaire-lib-frontend/lib/config/application.config';

import VisitedPlaceSection from './survey/templates/VisitedPlacesSection';

setApplicationConfiguration<EvolutionApplicationConfiguration>({
    <other application configurations>
    templateMapping: { ...appConfig.templateMapping, 'visitedPlaces': VisitedPlaceSection }
});

runClientApp();
```

2024-11-27 22:02 UTC, kaligrafy approved these changes

2024-11-28 19:40 UTC, samuel-duhaime requested changes
@tahini 
Isn't it really the best way to do that? 

There are two cons of this solution.

1. Every time we want to add a template, we need to make sure that we change the config in the right place and in Excel. There's a higher chance of errors and it's harder to maintain.
2. We won't be able to click directly on the sectionConfig template and see what's going on with the file using only a string (and not a variable to a file).

Maybe it's the only solution, but let's make sure we consider all our options.

2024-11-28 22:22 UTC, tahini commented
@samuel-duhaime Ton commentaire s'applique au générateur ou en général?

Si en général, il faut considérer qu'on ne veut pas que la configuration du questionnaire dépende d'un composant React et soit donc obligée d'aller dans le frontend. Donc le type `SectionConfig` ici ne peut pas être de type `React.ComponentType`. Et mettre les types dans le frontend ferait en sorte qu'il serait impossible au backend d'interagir avec, ce qui à long terme nous peinture dans un coin. Il doit donc obligatoirement y avoir une sorte de mapping en qq part, qui se fait actuellement automatiquement dans evolution pour avoir le template, mais qui pourrait être faite différemment.

Si tu parles juste du générateur, par contre, il y aurait en effet un moyen simple de générer qqc qui permettrait les 2, j'ai fixé ça un peu vite hier PM...

2024-11-29 16:31 UTC, samuel-duhaime commented
@tahini 
Mon commentaire s'appliquait au Générator et en Général. Mais, peut être que le mieux serait que le Generator génère le app-survey.tsx (ou dans ce cas-ci: le templateMapping).

Je suis ouvert à ton moyen simple ? 

Je veux juste éviter de devoir écrire qu'on utilise le template à 2 endroits différents (dans le code et le Generator), car c'est difficile à maintenir.

2024-11-29 19:51 UTC, tahini commented
@samuel-duhaime c'est fait, voir le commit message pour voir ce qui a été fait pour le générateur. On fournit même un squelette de template (pour s'assurer que le code généré compile)

2024-11-29 19:55 UTC, samuel-duhaime approved these changes
Merci, ça semble mieux.

2024-12-02 14:01 UTC, merged