Migrate types from inputTypes of evolution-generator to WidgetConfig of evolution-common
chairemobilite/evolution pull request #831
Opened 2024-12-18 22:11 UTC by samuel-duhaime

# Pull request
fix #532
Note: We still need to remove inputTypes, and migrate all the useful types. 

## Description
Migrate types from inputTypes of evolution-generator to WidgetConfig of evolution-common
Breaking changes: Validations type is now ValidationFunction Many types from inputTypes are now in WidgetConfig. You need to do 'yarn generateSurvey' for the Generator surveys

2024-12-20 13:28 UTC, tahini requested changes

2024-12-20 13:28 UTC, tahini commented on packages/evolution-common/src/services/questionnaire/types/WidgetConfig.ts
> +    groupedObjectConditional?: Conditional;
Dans ce cas-ci, ce n'est pas le même type de conditionnelle, ça ne peut pas retourner un array comme les autres avec valeur par défaut, il faut garder comme avant.

2024-12-20 13:28 UTC, tahini commented on packages/evolution-common/src/services/questionnaire/types/WidgetConfig.ts
> +        conditional?: Conditional;
Idem ici, malgré le nom du champ, on s'attend à recevoir un booléen uniquement, jamais un array.

2024-12-20 13:28 UTC, tahini commented on packages/evolution-generator/src/common/validations.tsx
> +                fr: "L'âge doit être au moins de 0.",
Je ne crois pas que le formatage va permettre ces changements...

2024-12-20 13:28 UTC, tahini commented on packages/evolution-common/src/services/questionnaire/types/WidgetConfig.ts
> +export type Conditional = boolean | ParsingFunction<boolean | [boolean] | [boolean, unknown]>;
Ce serait peut-être mieux de nommer ce type WidgetConditional, pour expliciter le fait que c'est une conditionnelle du type pour un widget, donc avec potentielle valeur par défaut, alors qu'un type Conditional serait uniquement booléen.

2024-12-20 13:30 UTC, tahini commented on packages/evolution-common/src/services/questionnaire/types/WidgetConfig.ts
> +export type Conditional = boolean | ParsingFunction<boolean | [boolean] | [boolean, unknown]>;
Aussi, en voyant les test failures, le type WidgetConditional devrait être juste une ParsingFunction, pas de booléen seulement. Tant qu'à mettre un booléen false, il faudrait désactiver le widget à la source, en le commentant dans la configuration de la section ou du groupe.

2025-03-11 15:21 UTC, samuel-duhaime commented
@Tahini, I was able to fuse and migrate the Evolution-Generator types with the Evolution-Common types. This will help to keep Evolution-Generator as a development repo (with only Python scripts). You can review it now.

2025-03-12 17:03 UTC, tahini requested changes

2025-03-12 19:21 UTC, samuel-duhaime commented on packages/evolution-common/src/services/questionnaire/types/WidgetConfig.ts
> +export type InputRangePartialType = {
I did use Pick and not Omit. There were fewer parameters to pick than to omit (because of the BaseQuestionType)

2025-03-12 20:01 UTC, tahini approved these changes

2025-03-12 20:06 UTC, merged